### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by SanderE1** [drewavis/mpl_python#6]
My question is how to change "Alien" speed.

Example:

```
    def speed(self):
        self.speedx += 1
```
Then:

 
`Alien.speed()`

It errors out with

> name 'self' is not defined

Why is this?

**Comment by drewavis** [comment]
I think the problem is you are calling speed on the Alien class, not an alien object.  Try:
alien.speed() 
(lower case, not capitalized) and see if that works.

Also, make sure your def speed() function is "inside" the Alien class (at the same indentation level as the init, and switch_direction() methods).
